image: way2web/pipeline-apps:latest

pipelines:
    default:
        - step:
            caches:
                - yarn
            script:
                - ./bitbucket-pipelines/assets.sh
    branches:
        develop:
            - step:
                caches:
                    - yarn
                script:
                    - ./bitbucket-pipelines/assets.sh
        master:
            - step:
                caches:
                    - yarn
                script:
                    - ./bitbucket-pipelines/assets.sh
                    - ./bitbucket-pipelines/npm.sh

definitions:
    caches:
        yarn: /usr/local/share/.cache/yarn/
